sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: qPSJOnSXgDaZQwncY45e4pI35DEDvzw7WXLM8SMa5esJrDXRFmL2Ai9dgbmEYAUiRDYQO3TBJ9Tif+Z6k53WN8dVftTXd5wOcIp1A+AuZactQf13KSswJIGUPYGsc9GBuI25qMfmElJYA7KpsihqxnnjWGXOVGIHaQrpbUxnz+AeM4BCo4bbnX/wQ42w7NDH+JhDemwqoai6gUJWmUBO3JBWStWy4cDWmhCWzeUSjblmQzzT/BGf0yJmpa0c0rUr1x+9QPrMUqlGew42erawNbxSnrlqTAMzBicfUpK7dvPbw+3Zl8OlxdLTOZTgU4Dh9FSt1yZcEgW023Ow5x7V+JP2W3WMqYFrCrslnGFOUduTjoSBiIT9FaklJeyyVbTqPp8t8zWIDi3/6HpjUiKNzCTLJEhdGmsw0lVb3EgftuN6VZmlqIm3VdIF+FXQB+YQBPsVZNKGltm9DNi3MQD3HcsD8tr7X8zvx0Bfzm2lsm+iCEoSpWNlrvsrX3QY8uAxAE7tZB4c9k+CpozqxzKR15npz8TtO0BDzkWpt6HZyJJ6X8P5ygaIr/0YPa0F1J08E0bMhjzVBiZRXk05ZxMb10KxZzk20o5tl+13PlYicdGUsdnuYGNKP69K8sA036zFxD3z83jb0KXTlgkQRI6KZUFLQ6IiTvCHyyFb7gdOQsU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Paradise-Lost_26
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy